package LW3;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: A1_Knowledges_Numbers <br>
 * @version generated on Sun Oct 04 15:40:40 MSK 2020 by Katherina
 */

public interface A1_Knowledges_Numbers extends Knowledges {

    /* ***************************************************
     * Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_knows
     */
     
    /**
     * Gets all property values for the A1_knows property.<p>
     * 
     * @returns a collection of values for the A1_knows property.
     */
    Collection<? extends Level_A1> getA1_knows();

    /**
     * Checks if the class has a A1_knows property value.<p>
     * 
     * @return true if there is a A1_knows property value.
     */
    boolean hasA1_knows();

    /**
     * Adds a A1_knows property value.<p>
     * 
     * @param newA1_knows the A1_knows property value to be added
     */
    void addA1_knows(Level_A1 newA1_knows);

    /**
     * Removes a A1_knows property value.<p>
     * 
     * @param oldA1_knows the A1_knows property value to be removed.
     */
    void removeA1_knows(Level_A1 oldA1_knows);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
