package LW3;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: A2_Skills_Describe_background_in_simple_terms <br>
 * @version generated on Sun Oct 04 15:40:40 MSK 2020 by Katherina
 */

public interface A2_Skills_Describe_background_in_simple_terms extends Skills {

    /* ***************************************************
     * Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_can
     */
     
    /**
     * Gets all property values for the A2_can property.<p>
     * 
     * @returns a collection of values for the A2_can property.
     */
    Collection<? extends Level_A2> getA2_can();

    /**
     * Checks if the class has a A2_can property value.<p>
     * 
     * @return true if there is a A2_can property value.
     */
    boolean hasA2_can();

    /**
     * Adds a A2_can property value.<p>
     * 
     * @param newA2_can the A2_can property value to be added
     */
    void addA2_can(Level_A2 newA2_can);

    /**
     * Removes a A2_can property value.<p>
     * 
     * @param oldA2_can the A2_can property value to be removed.
     */
    void removeA2_can(Level_A2 oldA2_can);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
