package LW3;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: B2_Knowledges_Text_structure <br>
 * @version generated on Sun Oct 04 15:40:40 MSK 2020 by Katherina
 */

public interface B2_Knowledges_Text_structure extends Knowledges {

    /* ***************************************************
     * Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_knows
     */
     
    /**
     * Gets all property values for the B2_knows property.<p>
     * 
     * @returns a collection of values for the B2_knows property.
     */
    Collection<? extends Level_B2> getB2_knows();

    /**
     * Checks if the class has a B2_knows property value.<p>
     * 
     * @return true if there is a B2_knows property value.
     */
    boolean hasB2_knows();

    /**
     * Adds a B2_knows property value.<p>
     * 
     * @param newB2_knows the B2_knows property value to be added
     */
    void addB2_knows(Level_B2 newB2_knows);

    /**
     * Removes a B2_knows property value.<p>
     * 
     * @param oldB2_knows the B2_knows property value to be removed.
     */
    void removeB2_knows(Level_B2 oldB2_knows);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
