package LW3;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: B2_Skills_Explain_a_viewpoint <br>
 * @version generated on Sun Oct 04 15:40:40 MSK 2020 by Katherina
 */

public interface B2_Skills_Explain_a_viewpoint extends Skills {

    /* ***************************************************
     * Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_can
     */
     
    /**
     * Gets all property values for the B2_can property.<p>
     * 
     * @returns a collection of values for the B2_can property.
     */
    Collection<? extends Level_B2> getB2_can();

    /**
     * Checks if the class has a B2_can property value.<p>
     * 
     * @return true if there is a B2_can property value.
     */
    boolean hasB2_can();

    /**
     * Adds a B2_can property value.<p>
     * 
     * @param newB2_can the B2_can property value to be added
     */
    void addB2_can(Level_B2 newB2_can);

    /**
     * Removes a B2_can property value.<p>
     * 
     * @param oldB2_can the B2_can property value to be removed.
     */
    void removeB2_can(Level_B2 oldB2_can);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
