package LW3;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: C1_Knowledges_Sarcasm <br>
 * @version generated on Sun Oct 04 15:40:40 MSK 2020 by Katherina
 */

public interface C1_Knowledges_Sarcasm extends Knowledges {

    /* ***************************************************
     * Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_knows
     */
     
    /**
     * Gets all property values for the C1_knows property.<p>
     * 
     * @returns a collection of values for the C1_knows property.
     */
    Collection<? extends Level_C1> getC1_knows();

    /**
     * Checks if the class has a C1_knows property value.<p>
     * 
     * @return true if there is a C1_knows property value.
     */
    boolean hasC1_knows();

    /**
     * Adds a C1_knows property value.<p>
     * 
     * @param newC1_knows the C1_knows property value to be added
     */
    void addC1_knows(Level_C1 newC1_knows);

    /**
     * Removes a C1_knows property value.<p>
     * 
     * @param oldC1_knows the C1_knows property value to be removed.
     */
    void removeC1_knows(Level_C1 oldC1_knows);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
