package LW3;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: C2_Knowledges_All_vocabulary <br>
 * @version generated on Sun Oct 04 15:40:40 MSK 2020 by Katherina
 */

public interface C2_Knowledges_All_vocabulary extends Knowledges {

    /* ***************************************************
     * Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_knows
     */
     
    /**
     * Gets all property values for the C2_knows property.<p>
     * 
     * @returns a collection of values for the C2_knows property.
     */
    Collection<? extends Level_C2> getC2_knows();

    /**
     * Checks if the class has a C2_knows property value.<p>
     * 
     * @return true if there is a C2_knows property value.
     */
    boolean hasC2_knows();

    /**
     * Adds a C2_knows property value.<p>
     * 
     * @param newC2_knows the C2_knows property value to be added
     */
    void addC2_knows(Level_C2 newC2_knows);

    /**
     * Removes a C2_knows property value.<p>
     * 
     * @param oldC2_knows the C2_knows property value to be removed.
     */
    void removeC2_knows(Level_C2 oldC2_knows);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
