package LW3;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun Oct 04 15:40:39 MSK 2020 by Katherina
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Knowledges_Alphabet
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A1_KNOWLEDGES_ALPHABET.<p>
     * 
     */
    public static final OWLClass CLASS_A1_KNOWLEDGES_ALPHABET = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Knowledges_Alphabet"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Knowledges_Basics_of_terms
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A1_KNOWLEDGES_BASICS_OF_TERMS.<p>
     * 
     */
    public static final OWLClass CLASS_A1_KNOWLEDGES_BASICS_OF_TERMS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Knowledges_Basics_of_terms"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Knowledges_Numbers
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A1_KNOWLEDGES_NUMBERS.<p>
     * 
     */
    public static final OWLClass CLASS_A1_KNOWLEDGES_NUMBERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Knowledges_Numbers"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Skills_Ask_for_help
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A1_SKILLS_ASK_FOR_HELP.<p>
     * 
     */
    public static final OWLClass CLASS_A1_SKILLS_ASK_FOR_HELP = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Skills_Ask_for_help"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Skills_Introduse_himself
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A1_SKILLS_INTRODUSE_HIMSELF.<p>
     * 
     */
    public static final OWLClass CLASS_A1_SKILLS_INTRODUSE_HIMSELF = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Skills_Introduse_himself"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Skills_Read_simple_words
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A1_SKILLS_READ_SIMPLE_WORDS.<p>
     * 
     */
    public static final OWLClass CLASS_A1_SKILLS_READ_SIMPLE_WORDS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Skills_Read_simple_words"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Skills_Understand_simple_clear_speach
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A1_SKILLS_UNDERSTAND_SIMPLE_CLEAR_SPEACH.<p>
     * 
     */
    public static final OWLClass CLASS_A1_SKILLS_UNDERSTAND_SIMPLE_CLEAR_SPEACH = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Skills_Understand_simple_clear_speach"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Skills_Write_simple_words
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A1_SKILLS_WRITE_SIMPLE_WORDS.<p>
     * 
     */
    public static final OWLClass CLASS_A1_SKILLS_WRITE_SIMPLE_WORDS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_Skills_Write_simple_words"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Knowledges_Prepositions
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A2_KNOWLEDGES_PREPOSITIONS.<p>
     * 
     */
    public static final OWLClass CLASS_A2_KNOWLEDGES_PREPOSITIONS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Knowledges_Prepositions"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Knowledges_Pronouns
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A2_KNOWLEDGES_PRONOUNS.<p>
     * 
     */
    public static final OWLClass CLASS_A2_KNOWLEDGES_PRONOUNS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Knowledges_Pronouns"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Knowledges_Words_connected_to_everyday_speach
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A2_KNOWLEDGES_WORDS_CONNECTED_TO_EVERYDAY_SPEACH.<p>
     * 
     */
    public static final OWLClass CLASS_A2_KNOWLEDGES_WORDS_CONNECTED_TO_EVERYDAY_SPEACH = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Knowledges_Words_connected_to_everyday_speach"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Skills_Communicate_in_simple_way
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A2_SKILLS_COMMUNICATE_IN_SIMPLE_WAY.<p>
     * 
     */
    public static final OWLClass CLASS_A2_SKILLS_COMMUNICATE_IN_SIMPLE_WAY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Skills_Communicate_in_simple_way"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Skills_Describe_background_in_simple_terms
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A2_SKILLS_DESCRIBE_BACKGROUND_IN_SIMPLE_TERMS.<p>
     * 
     */
    public static final OWLClass CLASS_A2_SKILLS_DESCRIBE_BACKGROUND_IN_SIMPLE_TERMS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Skills_Describe_background_in_simple_terms"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Skills_Understand_frequently_used_expressions
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A2_SKILLS_UNDERSTAND_FREQUENTLY_USED_EXPRESSIONS.<p>
     * 
     */
    public static final OWLClass CLASS_A2_SKILLS_UNDERSTAND_FREQUENTLY_USED_EXPRESSIONS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Skills_Understand_frequently_used_expressions"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Skills_Understand_sentences
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class A2_SKILLS_UNDERSTAND_SENTENCES.<p>
     * 
     */
    public static final OWLClass CLASS_A2_SKILLS_UNDERSTAND_SENTENCES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_Skills_Understand_sentences"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Knowledges_Spelling
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B1_KNOWLEDGES_SPELLING.<p>
     * 
     */
    public static final OWLClass CLASS_B1_KNOWLEDGES_SPELLING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Knowledges_Spelling"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Knowledges_Tenses
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B1_KNOWLEDGES_TENSES.<p>
     * 
     */
    public static final OWLClass CLASS_B1_KNOWLEDGES_TENSES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Knowledges_Tenses"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Knowledges_Words_related_to_plans
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B1_KNOWLEDGES_WORDS_RELATED_TO_PLANS.<p>
     * 
     */
    public static final OWLClass CLASS_B1_KNOWLEDGES_WORDS_RELATED_TO_PLANS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Knowledges_Words_related_to_plans"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Briefly_give_reasons_for_plans
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B1_SKILLS_BRIEFLY_GIVE_REASONS_FOR_PLANS.<p>
     * 
     */
    public static final OWLClass CLASS_B1_SKILLS_BRIEFLY_GIVE_REASONS_FOR_PLANS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Briefly_give_reasons_for_plans"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Deal_with_most_situations_where_language_needed
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B1_SKILLS_DEAL_WITH_MOST_SITUATIONS_WHERE_LANGUAGE_NEEDED.<p>
     * 
     */
    public static final OWLClass CLASS_B1_SKILLS_DEAL_WITH_MOST_SITUATIONS_WHERE_LANGUAGE_NEEDED = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Deal_with_most_situations_where_language_needed"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Describe_ambitions
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B1_SKILLS_DESCRIBE_AMBITIONS.<p>
     * 
     */
    public static final OWLClass CLASS_B1_SKILLS_DESCRIBE_AMBITIONS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Describe_ambitions"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Describe_dreams
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B1_SKILLS_DESCRIBE_DREAMS.<p>
     * 
     */
    public static final OWLClass CLASS_B1_SKILLS_DESCRIBE_DREAMS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Describe_dreams"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Describe_hopes
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B1_SKILLS_DESCRIBE_HOPES.<p>
     * 
     */
    public static final OWLClass CLASS_B1_SKILLS_DESCRIBE_HOPES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Describe_hopes"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Produce_simple_connected_text
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B1_SKILLS_PRODUCE_SIMPLE_CONNECTED_TEXT.<p>
     * 
     */
    public static final OWLClass CLASS_B1_SKILLS_PRODUCE_SIMPLE_CONNECTED_TEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Produce_simple_connected_text"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Understand_main_points_of_clear_input
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B1_SKILLS_UNDERSTAND_MAIN_POINTS_OF_CLEAR_INPUT.<p>
     * 
     */
    public static final OWLClass CLASS_B1_SKILLS_UNDERSTAND_MAIN_POINTS_OF_CLEAR_INPUT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_Skills_Understand_main_points_of_clear_input"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Knowledges_Linkers
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B2_KNOWLEDGES_LINKERS.<p>
     * 
     */
    public static final OWLClass CLASS_B2_KNOWLEDGES_LINKERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Knowledges_Linkers"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Knowledges_Tecnical_words
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B2_KNOWLEDGES_TECNICAL_WORDS.<p>
     * 
     */
    public static final OWLClass CLASS_B2_KNOWLEDGES_TECNICAL_WORDS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Knowledges_Tecnical_words"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Knowledges_Text_structure
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B2_KNOWLEDGES_TEXT_STRUCTURE.<p>
     * 
     */
    public static final OWLClass CLASS_B2_KNOWLEDGES_TEXT_STRUCTURE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Knowledges_Text_structure"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Skills_Explain_a_viewpoint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B2_SKILLS_EXPLAIN_A_VIEWPOINT.<p>
     * 
     */
    public static final OWLClass CLASS_B2_SKILLS_EXPLAIN_A_VIEWPOINT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Skills_Explain_a_viewpoint"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Skills_Interact_spontaneusly
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B2_SKILLS_INTERACT_SPONTANEUSLY.<p>
     * 
     */
    public static final OWLClass CLASS_B2_SKILLS_INTERACT_SPONTANEUSLY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Skills_Interact_spontaneusly"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Skills_Lead_technical_discussions
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B2_SKILLS_LEAD_TECHNICAL_DISCUSSIONS.<p>
     * 
     */
    public static final OWLClass CLASS_B2_SKILLS_LEAD_TECHNICAL_DISCUSSIONS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Skills_Lead_technical_discussions"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Skills_Produce_clear_detailed_text
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B2_SKILLS_PRODUCE_CLEAR_DETAILED_TEXT.<p>
     * 
     */
    public static final OWLClass CLASS_B2_SKILLS_PRODUCE_CLEAR_DETAILED_TEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Skills_Produce_clear_detailed_text"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Skills_Understand_the_main_ideas_of_complex_text
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class B2_SKILLS_UNDERSTAND_THE_MAIN_IDEAS_OF_COMPLEX_TEXT.<p>
     * 
     */
    public static final OWLClass CLASS_B2_SKILLS_UNDERSTAND_THE_MAIN_IDEAS_OF_COMPLEX_TEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_Skills_Understand_the_main_ideas_of_complex_text"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Knowledges_Abbreviations
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C1_KNOWLEDGES_ABBREVIATIONS.<p>
     * 
     */
    public static final OWLClass CLASS_C1_KNOWLEDGES_ABBREVIATIONS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Knowledges_Abbreviations"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Knowledges_Finer_shades_of_words
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C1_KNOWLEDGES_FINER_SHADES_OF_WORDS.<p>
     * 
     */
    public static final OWLClass CLASS_C1_KNOWLEDGES_FINER_SHADES_OF_WORDS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Knowledges_Finer_shades_of_words"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Knowledges_Sarcasm
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C1_KNOWLEDGES_SARCASM.<p>
     * 
     */
    public static final OWLClass CLASS_C1_KNOWLEDGES_SARCASM = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Knowledges_Sarcasm"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Skills_Express_himself_fluently_and_spontaneously
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C1_SKILLS_EXPRESS_HIMSELF_FLUENTLY_AND_SPONTANEOUSLY.<p>
     * 
     */
    public static final OWLClass CLASS_C1_SKILLS_EXPRESS_HIMSELF_FLUENTLY_AND_SPONTANEOUSLY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Skills_Express_himself_fluently_and_spontaneously"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Skills_Produce_clear_wellstructured_text
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C1_SKILLS_PRODUCE_CLEAR_WELLSTRUCTURED_TEXT.<p>
     * 
     */
    public static final OWLClass CLASS_C1_SKILLS_PRODUCE_CLEAR_WELLSTRUCTURED_TEXT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Skills_Produce_clear_wellstructured_text"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Skills_Recognise_implicit_meaning
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C1_SKILLS_RECOGNISE_IMPLICIT_MEANING.<p>
     * 
     */
    public static final OWLClass CLASS_C1_SKILLS_RECOGNISE_IMPLICIT_MEANING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Skills_Recognise_implicit_meaning"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Skills_Understand_a_wide_range_of_demanding
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C1_SKILLS_UNDERSTAND_A_WIDE_RANGE_OF_DEMANDING.<p>
     * 
     */
    public static final OWLClass CLASS_C1_SKILLS_UNDERSTAND_A_WIDE_RANGE_OF_DEMANDING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Skills_Understand_a_wide_range_of_demanding"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Skills_Use_language_flexibly
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C1_SKILLS_USE_LANGUAGE_FLEXIBLY.<p>
     * 
     */
    public static final OWLClass CLASS_C1_SKILLS_USE_LANGUAGE_FLEXIBLY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_Skills_Use_language_flexibly"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Knowledges_All_tenses
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C2_KNOWLEDGES_ALL_TENSES.<p>
     * 
     */
    public static final OWLClass CLASS_C2_KNOWLEDGES_ALL_TENSES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Knowledges_All_tenses"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Knowledges_All_vocabulary
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C2_KNOWLEDGES_ALL_VOCABULARY.<p>
     * 
     */
    public static final OWLClass CLASS_C2_KNOWLEDGES_ALL_VOCABULARY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Knowledges_All_vocabulary"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Skills_Differentiating_finer_shades_of_meaning
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C2_SKILLS_DIFFERENTIATING_FINER_SHADES_OF_MEANING.<p>
     * 
     */
    public static final OWLClass CLASS_C2_SKILLS_DIFFERENTIATING_FINER_SHADES_OF_MEANING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Skills_Differentiating_finer_shades_of_meaning"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Skills_Read_all_texts
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C2_SKILLS_READ_ALL_TEXTS.<p>
     * 
     */
    public static final OWLClass CLASS_C2_SKILLS_READ_ALL_TEXTS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Skills_Read_all_texts"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Skills_Reconstruct_arguments
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C2_SKILLS_RECONSTRUCT_ARGUMENTS.<p>
     * 
     */
    public static final OWLClass CLASS_C2_SKILLS_RECONSTRUCT_ARGUMENTS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Skills_Reconstruct_arguments"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Skills_Summarise_information
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C2_SKILLS_SUMMARISE_INFORMATION.<p>
     * 
     */
    public static final OWLClass CLASS_C2_SKILLS_SUMMARISE_INFORMATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Skills_Summarise_information"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Skills_Write_everything
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class C2_SKILLS_WRITE_EVERYTHING.<p>
     * 
     */
    public static final OWLClass CLASS_C2_SKILLS_WRITE_EVERYTHING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_Skills_Write_everything"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Knowledges
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class KNOWLEDGES.<p>
     * 
     */
    public static final OWLClass CLASS_KNOWLEDGES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Knowledges"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Language_levels
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LANGUAGE_LEVELS.<p>
     * 
     */
    public static final OWLClass CLASS_LANGUAGE_LEVELS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Language_levels"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEVEL.<p>
     * 
     */
    public static final OWLClass CLASS_LEVEL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_A1
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEVEL_A1.<p>
     * 
     */
    public static final OWLClass CLASS_LEVEL_A1 = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_A1"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_A2
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEVEL_A2.<p>
     * 
     */
    public static final OWLClass CLASS_LEVEL_A2 = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_A2"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_B1
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEVEL_B1.<p>
     * 
     */
    public static final OWLClass CLASS_LEVEL_B1 = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_B1"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_B2
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEVEL_B2.<p>
     * 
     */
    public static final OWLClass CLASS_LEVEL_B2 = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_B2"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_C1
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEVEL_C1.<p>
     * 
     */
    public static final OWLClass CLASS_LEVEL_C1 = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_C1"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_C2
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEVEL_C2.<p>
     * 
     */
    public static final OWLClass CLASS_LEVEL_C2 = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Level_C2"));

    /* ***************************************************
     * Class http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Skills
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SKILLS.<p>
     * 
     */
    public static final OWLClass CLASS_SKILLS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#Skills"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_can
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property A1_CAN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_A1_CAN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_can"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_knows
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property A1_KNOWS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_A1_KNOWS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A1_knows"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_can
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property A2_CAN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_A2_CAN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_can"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_knows
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property A2_KNOWS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_A2_KNOWS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#A2_knows"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_can
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property B1_CAN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_B1_CAN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_can"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_knows
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property B1_KNOWS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_B1_KNOWS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B1_knows"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_can
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property B2_CAN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_B2_CAN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_can"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_knows
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property B2_KNOWS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_B2_KNOWS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#B2_knows"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_can
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property C1_CAN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_C1_CAN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_can"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_knows
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property C1_KNOWS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_C1_KNOWS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C1_knows"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_can
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property C2_CAN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_C2_CAN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_can"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_knows
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property C2_KNOWS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_C2_KNOWS = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/katherina/ontologies/2020/9/untitled-ontology-9#C2_knows"));


}
